# Use root/example as user/password credentials
version: '3.8'

services:

  node-red:
    build: .
    # image: nodered/node-red:latest-22
    restart: unless-stopped
    ports:
      - "1891:1880"
    volumes:
      - ./node-red-data:/data

  front_bigc:
    container_name: front_bigcV2
    image: nginx:1.25.3-alpine-slim
    restart: unless-stopped
    ports:
      - "99:80"
    volumes:
      - ./nginx_bigc/website:/usr/share/nginx/html
      - ./nginx_bigc/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - node-red
